# Calibre-web - Web app for browsing, reading and downloading eBooks
# Docs: https://hub.docker.com/r/linuxserver/calibre-web

services:
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest

    env_file:

      - .env
