# File Browser - Web-based file manager
# Docs: https://filebrowser.org/

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest

    env_file:

      - .env
