# File Browser - Web-based file manager
# Docs: https://filebrowser.org/

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - ./database:/database
      - /media:/srv
    restart: unless-stopped
    networks:
      - homelab
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser.rule: Host(`files.fig.systems`) || Host(`files.edfig.dev`)
      traefik.http.routers.filebrowser.entrypoints: websecure
      traefik.http.routers.filebrowser.tls.certresolver: letsencrypt
      traefik.http.services.filebrowser.loadbalancer.server.port: 80
      traefik.http.routers.filebrowser.middlewares: tinyauth

networks:
  homelab:
    external: true
