services:
  lubelogger:
    image: 
    container_name: lubelogger
    restart: unless-stopped
    # ports:
    #   - ":"
    # volumes:
    #   - ./data:/data
    # environment:
    #   - VARIABLE=value
