# LubeLogger - Vehicle maintenance and fuel tracking
# Docs: https://github.com/hargata/lubelogger

services:
  lubelogger:
    container_name: lubelogger
    image: ghcr.io/hargata/lubelogger:latest

    env_file:

      - .env
