services:
  linkwarden:
    image: 
    container_name: linkwarden
    restart: unless-stopped
    # ports:
    #   - ":"
    # volumes:
    #   - ./data:/data
    # environment:
    #   - VARIABLE=value
