services:
  jellyseer:
    image: 
    container_name: jellyseer
    restart: unless-stopped
    # ports:
    #   - ":"
    # volumes:
    #   - ./data:/data
    # environment:
    #   - VARIABLE=value
